# This workflow will build a .NET project
name: Publish NuGet

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      
      - name: Use .NET 7.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
        
      - name: Packing
        run: |                    
          dotnet build XRPL.FoundationDataApi/XRPL.FoundationDataApi.csproj -c Release
          dotnet pack XRPL.FoundationDataApi/XRPL.FoundationDataApi.csproj -c Release
      - name: Publish GitHub
        run: |
          dotnet nuget push "**/*.nupkg" --skip-duplicate --source https://nuget.pkg.github.com/Platonenkov/index.json -k ${{secrets.GITHUBAPIKEY}}
      - name: Publish NuGet
        run: |
          dotnet nuget push "**/*.nupkg" --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGETAPIKEY}}
